api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('item/', views.item_api,name='item_api'),
]

djangoPractice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('todolist/', include('todoList.urls')),
    path('user/', include('user.urls')),
    path('weather/', include('weather.urls')),
    path('contactUs/', include('contactUs.urls')),
    path('bug/', include('bug.urls')),
    path('api/', include('api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoList/urls.py
from django.urls import path
from . import views

app_name = 'todoList'

urlpatterns = [
    path('', views.todoList, name = 'index'),
    path('<int:pk>/update/', views.updateTodoItem, name = 'update' ),
    path('<int:xxx>/delete/', views.deletedTodoItem, name = 'delete' ),
]

todoList/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UsersTodoList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)
    sessionKey = models.TextField()
    taskName = models.CharField(max_length=100)
    isDone = models.BooleanField(default=False)
    updatedDate = models.DateTimeField(auto_now=True)
    isDeleted = models.BooleanField(default=False)

    def __str__(self):
        return self.sessionKey
    

todoList/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import UsersTodoList
from datetime import datetime, timedelta
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.


def todoList(request):
    session_key = request.session.session_key
    if(not session_key):
        request.session.create()
        session_key = request.session.session_key

    if request.method == 'POST':
        newTask = request.POST.get('taskSubject')
        if len(newTask)<=3:
            messages.error(request, 'The task should have at least 4 characters.')
        else:
            if request.user.is_authenticated:
                myUser = request.user
                a = UsersTodoList(taskName=newTask, sessionKey=session_key, user=myUser)
                a.save()
            if not request.user.is_authenticated:
                a = UsersTodoList(taskName=newTask, sessionKey=session_key)
                a.save()

    if request.user.is_authenticated:
        myUser = request.user
        pageFilter = request.GET.get('filter')
        if pageFilter:
            if pageFilter.lower() == 'undone':
                taskList = UsersTodoList.objects.filter(user=myUser, isDeleted=False, isDone=False).order_by('updatedDate','id')
            elif pageFilter.lower() == 'done':
                taskList = UsersTodoList.objects.filter(user=myUser, isDeleted=False, isDone=True).order_by('updatedDate','id')
            elif pageFilter.lower() == 'deleted':
                taskList = UsersTodoList.objects.filter(user=myUser, isDeleted=True).order_by('updatedDate','id')
            elif pageFilter.lower() == 'other' and myUser.is_staff:
                taskList = UsersTodoList.objects.all().exclude(user=myUser).order_by('updatedDate','id')
            else:
                return redirect('todoList:index')
        else:
            taskList = UsersTodoList.objects.filter(user=myUser,isDeleted=False).order_by('isDone','updatedDate','id')
    
    
    else:
        pageFilter = request.GET.get('filter')
        if pageFilter:
            if pageFilter.lower() == 'undone':
                taskList = UsersTodoList.objects.filter(sessionKey=session_key, isDeleted=False, isDone=False).order_by('updatedDate','id')
            elif pageFilter.lower() == 'done':
                taskList = UsersTodoList.objects.filter(sessionKey=session_key, isDeleted=False, isDone=True).order_by('updatedDate','id')
            elif pageFilter.lower() == 'deleted':
                taskList = UsersTodoList.objects.filter(sessionKey=session_key, isDeleted=True).order_by('updatedDate','id')
            else:
                return redirect('todoList:index')
        else:
            taskList = UsersTodoList.objects.filter(sessionKey=session_key,isDeleted=False).order_by('isDone','updatedDate','id')


    daysKeep = 3
    past_date_before_daysKeep = timezone.now() - timedelta(days = daysKeep)
    ## Todolist.objects.filter(updatedDate__lte=daysKeep) ## bunu kullanamadık.

    filteredList = [i for i in taskList if (i.isDone and i.updatedDate >= past_date_before_daysKeep) or not i.isDone ]

    # yukarıdaki tek satıra alternatif olarak:
    """ filteredList = []
    for i in taskList:
        if (i.isDone  and i.updatedDate >= past_date_before_daysKeep) or not i.isDone:
            filteredList.append(i)
         """
    
    data = {
        'filteredList':filteredList,
        'sessionId':session_key,
    }
    return render(request, 'todoList/todoList.html',data)


def updateTodoItem(request, pk):
    try:
        todoItem = UsersTodoList.objects.get(pk=pk)
        if todoItem.isDone:
            todoItem.isDone = False
        else:
            todoItem.isDone = True
        todoItem.save()
        return redirect('todoList:index')
    except UsersTodoList.DoesNotExist:
        return redirect('todoList:index')
    

def deletedTodoItem(request, xxx):
    try:
        todoItem = UsersTodoList.objects.get(pk=xxx)
        if todoItem.isDeleted == True and request.user.is_staff:
            todoItem.isDeleted = False
        else:
            todoItem.isDeleted = True
        todoItem.save()
        return redirect('todoList:index')
    except UsersTodoList.DoesNotExist:
        return redirect('todoList:index')
    

templates/todoList/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To-Do Index</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 flex flex-col min-h-screen">
    {% include 'home/components/header.html' %}
    
    {% block mainContent%}
    {% endblock mainContent%}

    {% include 'todoList/components/footer.html' %}
</body>
</html>

templates/todoList/todoList.html
{% extends 'todoList/base.html' %}


{% block mainContent%}

  <!-- Main Content -->
  <main class="flex-grow p-6">
    <div class="max-w-md mx-auto bg-white rounded-lg shadow-md overflow-hidden md:max-w-2xl">
        <div class="md:flex">
            <div class="p-8 w-full">
                <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">To-Do List</div>
                <h2>Current SessionId: {{sessionId}}</h2>
                <div class="mt-4 flex justify-around">
                    <a href="{%url 'todoList:index' %}?filter=undone" class="px-4 py-2 bg-gray-200 text-gray-800 text-sm font-medium rounded-md hover:bg-gray-300">Undone</a>
                    <a href="{%url 'todoList:index' %}?filter=done" class="px-4 py-2 bg-gray-200 text-gray-800 text-sm font-medium rounded-md hover:bg-gray-300">Done</a>
                    <a href="{%url 'todoList:index' %}?filter=deleted" class="px-4 py-2 bg-gray-200 text-gray-800 text-sm font-medium rounded-md hover:bg-gray-300">Deleted</a>
                    {% if user.is_staff%}
                    <a href="{%url 'todoList:index' %}?filter=other" class="px-4 py-2 bg-gray-200 text-gray-800 text-sm font-medium rounded-md hover:bg-gray-300">Others</a>
                    {% endif %}
                </div>

                <div class="mt-2">
                    <ul class="space-y-4">
                        {% for task in filteredList%}
                        <li class="flex items-center justify-between">
                            {% if task.isDone %}
                            <span class="text-gray-700"> {% if task.user.id != user.id %}    {{task.user}} - {% endif%} <strike>{{task.taskName}}</strike></span>
                            {% else  %}
                            <span class="text-gray-700"> {% if task.user.id != user.id %}    {{task.user}} -  {% endif%} {{task.taskName}}</span>
                            {% endif %}
                            <div>
                                {% if task.isDone %}
                                <a href="{% url 'todoList:update' task.id%}" class="px-2 py-1 bg-yellow-500 text-white text-xs font-medium rounded-md hover:bg-yellow-700">Undone</a>
                                {% else  %}
                                <a href="{% url 'todoList:update' task.id%}" class="px-2 py-1 bg-green-500 text-white text-xs font-medium rounded-md hover:bg-green-700">Done</a>
                                {% endif %}
                                
                                {% if task.isDeleted and not user.is_staff %}
                                <button type='button' class="px-2 py-1  text-xs font-medium rounded-md ml-2 cursor-not-allowed" disabled>Already Deleted</button>
                                {% elif task.isDeleted and user.is_staff%}
                                <a href= "{% url 'todoList:delete' task.id%}" class="px-2 py-1 bg-blue-500 text-white text-xs font-medium rounded-md hover:bg-blue-700 ml-2" >Undelete</a>
                                {% else %}
                                <a href= "{% url 'todoList:delete' task.id%}" class="px-2 py-1 bg-red-500 text-white text-xs font-medium rounded-md hover:bg-red-700 ml-2" >Delete</a>
                                {% endif %}
                                
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mt-4">
                    {% if messages %}
                    {% for message in messages%}
                    <div id="notification" class="mt-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded-md">
                        {{message}}
                    </div>
                    {% endfor%}
                    {% endif %}
                    <form method='POST'> 
                        {% csrf_token %}
                        <input type="text" name='taskSubject' placeholder="New task..." class="px-3 py-2 border rounded-md w-full mb-2">
                        <input type="submit" class="px-4 py-2 bg-indigo-500 text-white text-sm font-medium rounded-md hover:bg-indigo-700" value='Add task'>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>


{% endblock mainContent%}